### ISSUE TITLE
API 연결 

### ISSUE THREAD

**Issue by rachel490** [rachel490/gifticon_next13#18]
## Tasks

- [ ] axios instance 셋업
- [ ] fetcher 함수 작성
- [ ] react query hook 작성
- [ ] API 연결
  - [ ] 홈 페이지
  - [ ] 브랜드 페이지
  - [ ] 메뉴목록 페이지
  - [ ] 메뉴상세 페이지
