### ISSUE TITLE
Card 구현

### ISSUE THREAD

**Issue by rachel490** [rachel490/gifticon_next13#7]
## Tasks
- [ ] 카드 컴포넌트 재사용성있게 구현
   - [ ] 땡처리 리스트 카드
   - [ ] 메뉴 리스트 카드
   - [ ] 메뉴 상세 카드
- [ ] 최대한 반응형 고려

<img width="220" alt="Screenshot 2023-05-02 at 6 24 28 AM" src="https://user-images.githubusercontent.com/72786354/235534102-7aba4968-c693-4196-b62f-6aafe237fa48.png">
